### ISSUE TITLE
ISO 639

### ISSUE THREAD

**Issue by melanieWacker** [cul/AC-RDF-Mapping#10]
@simosacchi FYI: I noticed that this example is using the language code from ISO 639-1. In our other collections we are generally using ISO 639-2

**Comment by simosacchi** [comment]
Ok @melanieWacker I'll change the language URI to 639-2

**Comment by simosacchi** [comment]
Fixed in https://github.com/cul/AC-RDF-Mapping/commit/848d8ac51fa7d754be80601f20196a45a77a13dc
