### ISSUE TITLE
Volume and issue info

### ISSUE THREAD

**Issue by simosacchi** [cul/AC-RDF-Mapping#2]
Which predicate to use for volume and issue information? @melanieWacker 

Also, in terms of modeling, I was thinking of modeling a journal entity either at the work or collection level connected to the article (another work) using bf:partOf (or something like that), so is it ok to push the issue and volume info at the article level?

**Comment by melanieWacker** [comment]
If I am understanding your question correctly, it would have to be on the article level since the specific issue and volume relate to the article, not the journal as a whole and that's what the partOf property would link to.

**Comment by simosacchi** [comment]
Thanks @melanieWacker closing this one.
