### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by melanieWacker** [cul/AC-RDF-Mapping#5]
@simosacchi the example is labeled as "Journal Article with related dataset", but when I follow the exact link it shows the dataset only. So are you also including the metadata of the journal article located here: http://academiccommons.columbia.edu/catalog/ac:177633 into your modeling?

**Comment by simosacchi** [comment]
You are right!! I fixed the DOI in https://github.com/cul/AC-RDF-Mapping/commit/b5398a21b463b899ec1b69a8e2fabd6619add40b
